### ISSUE TITLE
[Feature Request] - selection of bouquet

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#2]
Feature Request:

Option in config.js to select a bouquet.

I have 3 bouquets, of which only the Favourites (TV) is listed.
It would be nice to have an option like:

apiBouquet: "MyBouquet (TV)",

Should default to "Favourites (TV)".

**Comment by Ax-LED** [comment]
@evroom 
Hi erik, you wanted to select a bouquet:

> Okay.
Let's say I have the bouquet "MagicMirror (TV)", could there be an option to use this one, instead of the default "Favourites (TV)" ?
I assume "Favourites (TV)" is the default.

Please check the dev branch of my module.
1. Rename your MMM-Dreambox folder to _MMM-Dreambox (for example)
2. do a `git clone --branch dev https://github.com/Ax-LED/MMM-Dreambox.git` in your modules folder
3. add new parameters to your config.js, as descriped in readme. (see apibouquet and listmax).

Regards

AxLED
